"""Type stubs for LogFire."""

from typing import Any, Callable, Dict, Optional, TypeVar, overload

T = TypeVar("T")
SpanCallback = Callable[["Span"], T]

def configure(
    api_key: Optional[str] = None,
    project_id: Optional[str] = None,
    service_name: Optional[str] = None,
    environment: Optional[str] = None,
    **kwargs: Any,
) -> None: ...
def info(message: str, **attributes: Any) -> None: ...
def error(message: str, **attributes: Any) -> None: ...
def warning(message: str, **attributes: Any) -> None: ...
def debug(message: str, **attributes: Any) -> None: ...
def instrument_httpx() -> None: ...
def instrument_fastapi() -> None: ...
def instrument_asyncio() -> None: ...
def shutdown() -> None: ...

class Span:
    def __enter__(self) -> "Span": ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    def set_attributes(self, attributes: Dict[str, Any]) -> None: ...
    def set_status(self, status: str, description: Optional[str] = None) -> None: ...

@overload
def span(name: str) -> Span: ...
@overload
def span(name: str, **attributes: Any) -> Span: ...

class metrics:
    @staticmethod
    def counter(name: str, description: Optional[str] = None) -> "Counter": ...

class Counter:
    def add(self, value: int, attributes: Optional[Dict[str, Any]] = None) -> None: ...

# Pydantic AI integration
class pydantic_ai:
    @staticmethod
    def configure_pydantic_ai_instrumentation() -> None: ...
