import argparse
import logging
import os
from typing import Any, ClassVar, Optional, cast

import logfire  # Add logfire import
from dotenv import load_dotenv
from fastapi import FastAPI
from mcp.server.fastmcp import FastMCP
from pydantic import BaseModel, Field
from pydantic_ai import Agent

from pydanticai_api_template.utils.observability import setup_logfire

# Load environment variables
load_dotenv()

# Configure logging
logger = logging.getLogger(__name__)

# Initialize the OpenAI agent
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# Initialize LogFire if enabled
setup_logfire(service_name="pydanticai-mcp-server")


# Define Pydantic models for MCP server
class ChatRequest(BaseModel):
    """Model for chat request to the MCP server."""

    message: str = Field(..., description="The user's message to the AI agent.")

    model_config: ClassVar[dict[str, Any]] = {
        "json_schema_extra": {"example": {"message": "Tell me about Pydantic"}}
    }


class ChatResponse(BaseModel):
    """Model for chat response from the MCP server."""

    reply: str = Field(..., description="The AI agent's response.")

    model_config: ClassVar[dict[str, Any]] = {
        "json_schema_extra": {
            "example": {
                "reply": (
                    "Pydantic is a Python library for data validation "
                    "and settings management."
                )
            }
        }
    }


class StoryIdea(BaseModel):
    """Model for story ideas generated by the AI."""

    title: str = Field(..., description="The title of the story idea.")
    premise: str = Field(..., description="A brief description of the story premise.")

    model_config: ClassVar[dict[str, Any]] = {
        "json_schema_extra": {
            "example": {
                "title": "The Last Colony",
                "premise": (
                    "On a distant planet, the last human colony fights for survival "
                    "against an evolving alien ecosystem."
                ),
            }
        }
    }


# Initialize AI agent
try:
    ai_agent: Optional[Agent] = (
        Agent("openai:gpt-4o", result_type=ChatResponse) if OPENAI_API_KEY else None
    )

    # Initialize story agent
    story_agent: Optional[Agent] = (
        Agent("openai:gpt-4o", result_type=StoryIdea) if OPENAI_API_KEY else None
    )

    if ai_agent:
        logger.info("PydanticAI Agent initialized with openai:gpt-4o for MCP server")
    else:
        logger.warning(
            "PydanticAI Agent not initialized due to missing OPENAI_API_KEY."
        )
except Exception as e:
    logger.exception(f"Error initializing PydanticAI Agent: {e}")
    ai_agent = None

# Create FastMCP server
server = FastMCP("PydanticAI API MCP Server")


@server.tool()
async def chat(message: str) -> str:
    """Chat with the AI assistant

    Send a message to the AI assistant and receive a response.
    """
    with logfire.span("mcp_chat", message=message[:100]) as span:
        if not ai_agent:
            span.set_status("error", "AI service not available")
            return "AI service is not available. Please check server configuration."

        try:
            # Create a properly typed request object
            request = ChatRequest(message=message)

            # Ensure the agent is properly typed for mypy
            assert ai_agent is not None

            result: Any = await ai_agent.run(request.message)

            # Properly handle the response based on its type
            # Access reply attribute directly rather than through fields
            response_data = result.data
            if hasattr(response_data, "reply"):
                reply = str(response_data.reply)
                span.set_attributes({"response_length": len(reply)})
                return reply
            reply = str(response_data)
            span.set_attributes({"response_length": len(reply)})
            return reply
        except Exception as e:
            logger.exception(f"Error in MCP chat tool: {e}")
            span.set_status("error", str(e))
            return f"An error occurred while processing your request: {str(e)}"


@server.tool()
async def story(message: str) -> dict:
    """Generate a creative story idea

    Generate a story idea with a title and premise based on the input.
    You can specify genre, themes, or characters.

    Examples:
    - "Give me a sci-fi story about time travel"
    - "Create a fantasy story with dragons"
    - "Write a mystery set in Victorian London"
    """
    with logfire.span("mcp_story", message=message[:100]) as span:
        if not story_agent:
            span.set_status("error", "AI service not available")
            return {
                "error": "AI service is not available. Please check server configuration."
            }

        try:
            # Enhance the prompt to get high-quality story ideas
            enhanced_prompt = (
                f"Generate a creative and original story idea based on this input: "
                f"{message}"
            )

            # Ensure the agent is properly typed for mypy
            assert story_agent is not None

            result = await story_agent.run(enhanced_prompt)

            # Return the story idea as a dictionary
            # Access attributes directly rather than through fields
            response_data = result.data
            if hasattr(response_data, "title") and hasattr(response_data, "premise"):
                story_dict = {
                    "title": response_data.title,
                    "premise": response_data.premise,
                }
                span.set_attributes(
                    {
                        "story_title": story_dict["title"],
                        "premise_length": len(story_dict["premise"]),
                    }
                )
                return story_dict
            span.set_status("error", "Failed to generate proper story idea")
            return {"error": "Failed to generate a proper story idea"}
        except Exception as e:
            logger.exception(f"Error in MCP story tool: {e}")
            span.set_status("error", str(e))
            return {
                "error": f"An error occurred while processing your request: {str(e)}"
            }


def create_app() -> FastAPI:
    """Create a FastAPI app with the MCP server"""
    # Create the SSE app and use it directly as the root app
    # This makes the SSE endpoint available at / instead of /sse
    return cast(FastAPI, server.sse_app())


def run_standalone() -> None:
    """Run the MCP server standalone in SSE mode"""
    import uvicorn

    # Parse command line arguments
    parser = argparse.ArgumentParser(description="Run the MCP server")
    parser.add_argument(
        "--host",
        default=os.getenv("MCP_HOST", "0.0.0.0"),
        help="Host to bind the server to",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=int(os.getenv("MCP_PORT", "3001")),
        help="Port to bind the server to",
    )
    args = parser.parse_args()

    host = args.host
    port = args.port

    logger.info(f"Starting MCP server on {host}:{port}")
    uvicorn.run(create_app(), host=host, port=port)


if __name__ == "__main__":
    run_standalone()
